var domesticCases = [
  {
    "id": 1,
    "sex": "여",
    "age": 35,
    "nation": "중국",
    "wuhan": "O",
    "arriveDate": 1.19,
    "confirmDate": "1.20",
    "hospital": "인천의료원",
    "contact": 45,
    "contactCheck": "4명 음성"
  },
  {
    "id": 2,
    "sex": "남",
    "age": 55,
    "nation": "한국",
    "wuhan": "O",
    "arriveDate": 1.22,
    "confirmDate": "1.24",
    "hospital": "국립중앙\n의료원",
    "contact": 75,
    "contactCheck": "7명 음성"
  },
  {
    "id": 3,
    "sex": "남",
    "age": 54,
    "nation": "한국",
    "wuhan": "O",
    "arriveDate": 1.2,
    "confirmDate": "1.26",
    "hospital": "명지병원",
    "contact": 98,
    "contactCheck": "2명 음성\n1명 양성"
  },
  {
    "id": 4,
    "sex": "남",
    "age": 55,
    "nation": "한국",
    "wuhan": "O",
    "arriveDate": 1.2,
    "confirmDate": "1.27",
    "hospital": "분당서울대병원",
    "contact": 172,
    "contactCheck": "2명 음성"
  },
  {
    "id": 5,
    "sex": "남",
    "age": 33,
    "nation": "한국",
    "wuhan": "O",
    "arriveDate": 1.24,
    "confirmDate": "1.3",
    "hospital": "서울의료원",
    "contact": 33,
    "contactCheck": "1명 양성"
  },
  {
    "id": 6,
    "sex": "남",
    "age": 55,
    "nation": "한국",
    "wuhan": "X",
    "arriveDate": "-",
    "confirmDate": "1.3",
    "hospital": "서울대병원",
    "contact": 25,
    "contactCheck": "2명 양성"
  },
  {
    "id": 7,
    "sex": "남",
    "age": 28,
    "nation": "한국",
    "wuhan": "O",
    "arriveDate": 1.23,
    "confirmDate": "1.31",
    "hospital": "서울의료원",
    "contact": 21,
    "contactCheck": "-"
  },
  {
    "id": 8,
    "sex": "여",
    "age": 62,
    "nation": "한국",
    "wuhan": "O",
    "arriveDate": 1.23,
    "confirmDate": "1.31",
    "hospital": "원광대병원",
    "contact": 72,
    "contactCheck": "2명 음성\n1명 검사중"
  },
  {
    "id": 9,
    "sex": "여",
    "age": 28,
    "nation": "한국",
    "wuhan": "X",
    "arriveDate": "-",
    "confirmDate": "1.31",
    "hospital": "서울의료원",
    "contact": 2,
    "contactCheck": "-"
  },
  {
    "id": 10,
    "sex": "여",
    "age": 54,
    "nation": "한국",
    "wuhan": "X",
    "arriveDate": "-",
    "confirmDate": "1.31",
    "hospital": "서울대병원",
    "contact": 2,
    "contactCheck": "-"
  },
  {
    "id": 11,
    "sex": "남",
    "age": 25,
    "nation": "한국",
    "wuhan": "X",
    "arriveDate": "-",
    "confirmDate": "1.31",
    "hospital": "서울대병원",
    "contact": "조사중",
    "contactCheck": "-"
  },
  {
    "id": 12,
    "sex": "남",
    "age": 48,
    "nation": "중국",
    "wuhan": "X",
    "arriveDate": 1.19,
    "confirmDate": "2.1",
    "hospital": "분당서울대병원",
    "contact": 138,
    "contactCheck": "1명 양성\n1명 검사중"
  },
  {
    "id": 13,
    "sex": "남",
    "age": 28,
    "nation": "한국",
    "wuhan": "O",
    "arriveDate": 1.31,
    "confirmDate": "2.2",
    "hospital": "국립중앙의료원",
    "contact": "조사중",
    "contactCheck": "-"
  },
  {
    "id": 14,
    "sex": "여",
    "age": 40,
    "nation": "중국",
    "wuhan": "X",
    "arriveDate": "-",
    "confirmDate": "2.2",
    "hospital": "분당서울대병원",
    "contact": "조사중",
    "contactCheck": "-"
  },
  {
    "id": 15,
    "sex": "남",
    "age": 43,
    "nation": "한국",
    "wuhan": "O",
    "arriveDate": 1.2,
    "confirmDate": "2.2",
    "hospital": "국군수도병원",
    "contact": "조사중",
    "contactCheck": "-"
  }
]